# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "06a6dcc12a0e46225e948d3386a6650f"
name = "App-with-remix"
handle = "app-with-remix-2"
application_url = "https://definitions-allocation-ceiling-closest.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"                          

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,write_discounts,read_products"

[auth]
redirect_urls = ["https://definitions-allocation-ceiling-closest.trycloudflare.com/auth/callback", "https://definitions-allocation-ceiling-closest.trycloudflare.com/auth/shopify/callback", "https://definitions-allocation-ceiling-closest.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
